/** Metro Manila first, then other Philippine cities. Values are stored on stores.city. */
export const METRO_MANILA_CITIES = [
  'Caloocan',
  'Las Piñas',
  'Makati',
  'Malabon',
  'Mandaluyong',
  'Manila',
  'Marikina',
  'Muntinlupa',
  'Navotas',
  'Parañaque',
  'Pasay',
  'Pasig',
  'Pateros',
  'Quezon City',
  'San Juan',
  'Taguig',
  'Valenzuela',
] as const;

export const OTHER_PH_CITIES = [
  'Alaminos',
  'Angeles',
  'Antipolo',
  'Bacolod',
  'Bacoor',
  'Bago',
  'Baguio',
  'Bais',
  'Balanga',
  'Batac',
  'Batangas City',
  'Bayawan',
  'Baybay',
  'Bayugan',
  'Biñan',
  'Bislig',
  'Bogo',
  'Borongan',
  'Butuan',
  'Cabadbaran',
  'Cabanatuan',
  'Cabuyao',
  'Cadiz',
  'Cagayan de Oro',
  'Calamba',
  'Calapan',
  'Calbayog',
  'Candon',
  'Canlaon',
  'Carcar',
  'Catbalogan',
  'Cauayan',
  'Cavite City',
  'Cebu City',
  'Cotabato City',
  'Dagupan',
  'Danao',
  'Dapitan',
  'Dasmariñas',
  'Davao City',
  'Digos',
  'Dipolog',
  'Dumaguete',
  'El Salvador',
  'Escalante',
  'Gapan',
  'General Santos',
  'General Trias',
  'Gingoog',
  'Guihulngan',
  'Himamaylan',
  'Iligan',
  'Iloilo City',
  'Imus',
  'Iriga',
  'Isabela (Basilan)',
  'Island Garden City of Samal',
  'Kabankalan',
  'Kidapawan',
  'Koronadal',
  'La Carlota',
  'Lamitan',
  'Laoag',
  'Lapu-Lapu',
  'Legazpi',
  'Ligao',
  'Lipa',
  'Lucena',
  'Maasin',
  'Malaybalay',
  'Malolos',
  'Mandaue',
  'Marawi',
  'Masbate City',
  'Mati',
  'Meycauayan',
  'Naga (Camarines Sur)',
  'Naga (Cebu)',
  'Olongapo',
  'Ormoc',
  'Oroquieta',
  'Ozamiz',
  'Pagadian',
  'Palayan',
  'Panabo',
  'Passi',
  'Puerto Princesa',
  'Roxas',
  'Sagay',
  'San Carlos (Negros Occidental)',
  'San Carlos (Pangasinan)',
  'San Fernando (La Union)',
  'San Fernando (Pampanga)',
  'San Jose (Nueva Ecija)',
  'San Jose del Monte',
  'San Pablo',
  'San Pedro',
  'Santa Rosa',
  'Santiago',
  'Silay',
  'Sipalay',
  'Sorsogon City',
  'Surigao City',
  'Tabaco',
  'Tabuk',
  'Tacloban',
  'Tacurong',
  'Tagaytay',
  'Tagbilaran',
  'Tagum',
  'Talisay (Cebu)',
  'Talisay (Negros Occidental)',
  'Tanauan',
  'Tandag',
  'Tangub',
  'Tanjay',
  'Tarlac City',
  'Tayabas',
  'Toledo',
  'Trece Martires',
  'Tuguegarao',
  'Urdaneta',
  'Valencia',
  'Victorias',
  'Vigan',
  'Zamboanga City',
] as const;

/** Official Taguig barangays, including Napindan and the EMBO barangays. */
export const TAGUIG_BARANGAYS = [
  'Bagumbayan',
  'Bambang',
  'Calzada',
  'Cembo',
  'Central Bicutan',
  'Central Signal Village',
  'Comembo',
  'East Rembo',
  'Fort Bonifacio',
  'Hagonoy',
  'Ibayo-Tipas',
  'Katuparan',
  'Ligid-Tipas',
  'Lower Bicutan',
  'Maharlika Village',
  'Napindan',
  'New Lower Bicutan',
  'North Daang Hari',
  'North Signal Village',
  'Palingon',
  'Pembo',
  'Pinagsama',
  'Pitogo',
  'Post Proper Northside',
  'Post Proper Southside',
  'Rizal',
  'San Miguel',
  'Santa Ana',
  'South Cembo',
  'South Daang Hari',
  'South Signal Village',
  'Tanyag',
  'Tuktukan',
  'Upper Bicutan',
  'Ususan',
  'Wawa',
  'West Rembo',
  'Western Bicutan',
] as const;

export type PlaceOption = { value: string; label: string; group?: string };

export const CITY_OPTIONS: PlaceOption[] = [
  ...METRO_MANILA_CITIES.map((city) => ({ value: city, label: city, group: 'Metro Manila' })),
  ...OTHER_PH_CITIES.map((city) => ({ value: city, label: city, group: 'Other cities' })),
];

export function barangaysForCity(city: string): string[] {
  if (city === 'Taguig') return [...TAGUIG_BARANGAYS];
  return [];
}

export function barangayOptions(city: string): PlaceOption[] {
  return barangaysForCity(city).map((name) => ({ value: name, label: name }));
}

export function storeCityName(store: { city?: string | null }): string {
  const city = (store.city || '').trim();
  return city || 'Unspecified';
}
